### ISSUE TITLE
Questions about the Shapenet dataset normalisation and gridding operation.

### ISSUE THREAD

**Issue by Emma2010** [hzxie/GRNet#23]
Thank you for the great paper and code!!

I have a few questions:

- I noticed that the precomputed ShapeNet dataset seems to be normalised in the range (-0.5, 0.5) rather than (-1, 1) and the pointclouds after gridding only occupy a [32, 32, 32]  subset of the [64, 64, 64] grid. Is that expected? When I tried to pass on pointclouds normalised in the range (-1, 1) I got an error (I'm not sure it's related).
- From the paper, I would have expected the grid vertices (the output of the Gridding layer) to have values in the range 0-1, but I see much larger values. Did I misunderstand the gridding operation?

Thank you very much

**Comment by hzxie** [comment]
Sorry, I can't remember the details clearly.

- I remember that the coordinates of the points in the ShapeNet datasets in the range of `(-1, 1)`. Did you analyze statistically the whole dataset about the maximum and minimum values of the coordinates? 
- Could you provide the error stack trace? **BTW,** please make sure that the coordinates are ranged in `(-1, 1)` instead of `[-1, 1]`.
- According to the code below, the output values of Gridding may be larger than 1. Because the values may come from multiple points. For example, there are multiple points in the same grid cell.

https://github.com/hzxie/GRNet/blob/335259235804fa30b0e89e0e257d886687bfb6f3/extensions/gridding/gridding.cu#L135-L176

Hope the answer helps.

**Comment by hzxie** [comment]
According to Eq.2 in the paper, the output of Gridding is divided by the number of points in the neighborhood, and I remember I did it. 
However, I can't find it in the code. If you find it, please tell me.
